# Generated by Django 5.0.3 on 2024-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='picture')),
            ],
        ),
    ]
